/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/history`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth/otp`; params?: Router.UnknownOutputParams; } | { pathname: `/Auth/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/Tabs/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Tabs/history`; params?: Router.UnknownOutputParams; } | { pathname: `/Tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Tabs/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/Auth/otp${`?${string}` | `#${string}` | ''}` | `/Auth/reset-password${`?${string}` | `#${string}` | ''}` | `/Tabs/dashboard${`?${string}` | `#${string}` | ''}` | `/Tabs/history${`?${string}` | `#${string}` | ''}` | `/Tabs/profile${`?${string}` | `#${string}` | ''}` | `/Tabs/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/Auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/history`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Tabs/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
